spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/parser?cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        type: trace
        format_sql: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        generate_statistics: false
        order_inserts: true
        order_updates: true